CREATE TABLE HELLO(ID INTEGER, MESSAGE VARCHAR(20));
CREATE TABLE EQ(
	EPIC VARCHAR(20),
	COMPANYNAME VARCHAR(100),
	ASSETTYPE VARCHAR(100),
	SECTOR  VARCHAR(100),
	CURRENCY VARCHAR(20),
	DATETIME VARCHAR(20),
	PRICE FLOAT,);
CREATE TABLE PORTFOLIO(
    PID INT,
    NAME VARCHAR(250), 
    MANAGER VARCHAR(100),
    CASH INT,
    CURRENCY VARCHAR(3),
    BENCHMARK VARCHAR(1));
CREATE TABLE HOLDINGS(
    PID INT, EPIC VARCHAR(20), NO_SHARES INT, TYPE VARCHAR (10), TIME VARCHAR(20));
